/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package vmasm.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 5;
  /** RegularExpression Id. */
  int JUMP = 6;
  /** RegularExpression Id. */
  int MOV = 7;
  /** RegularExpression Id. */
  int SUB = 8;
  /** RegularExpression Id. */
  int LABEL = 9;
  /** RegularExpression Id. */
  int MUL = 10;
  /** RegularExpression Id. */
  int POP = 11;
  /** RegularExpression Id. */
  int PUSH = 12;
  /** RegularExpression Id. */
  int DOL = 13;
  /** RegularExpression Id. */
  int PER = 14;
  /** RegularExpression Id. */
  int NUM = 15;
  /** RegularExpression Id. */
  int DIG = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"add\"",
    "\"jmp\"",
    "\"mov\"",
    "\"sub\"",
    "<LABEL>",
    "\"mul\"",
    "\"pop\"",
    "\"push\"",
    "\"$\"",
    "\"%\"",
    "<NUM>",
    "<DIG>",
  };

}
